CI DC INTEGRATION

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,22 +49,61 @@ jobs:
           # Obtener solo los archivos modificados con extensión .sql
           git diff --name-only HEAD^ HEAD | grep '\.sql$' > modified_files.txt || true
           cat modified_files.txt
+
+      
+      - name: Validate SQL files
+        run: |
+          # Iterar sobre los archivos modificados
+          for file in $(cat modified_files.txt); do
+            echo "Validating $file"
+            
+            # Verificar que el archivo contenga solo sentencias permitidas
+            if ! grep -Ei '^(ALTER TASK|CREATE TASK|DELETE TASK)' "$file"; then
+              echo "ERROR: $file contiene sentencias no permitidas."
+              exit 1
+            fi
+          done
+        shell: bash
  
       # ============ DEV ============
-      - name: Deploy Snowflake objects to DEV
+      name: Deploy Snowflake objects to DEV
         if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'DEV') }}
         env:
           SNOWFLAKE_CONNECTIONS_ACCOUNT: ${{ secrets.SNOWFLAKE_CONNECTIONS_ACCOUNT }}
           SNOWFLAKE_CONNECTIONS_USER: ${{ secrets.SNOWFLAKE_CONNECTIONS_USER }}
           SNOWFLAKE_CONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTION_PASSWORD }}
           SNOWFLAKE_CONNECTIONS_ROLES: ${{ secrets.SNOWFLAKE_CONNECTIONS_ROLES }}
-          SNOWFLAKE_CONNECTION_WAREHOUSE: ${{ secrets.SNOWFLAKE_CONNECTION_WAREHOUSE }}
+          SNOWFLAKE_CONNECTION_WAREHOUSE: ${{ secrets.SNOWFLAKE_CONNECTIONS_WAREHOUSE }}
           SNOWFLAKE_CONNECTIONS_DATABASE: ${{ secrets.SNOWFLAKE_CONNECTIONS_DATABASE }}
           SNOWFLAKE_CONNECTIONS_SCHEMA: ${{ secrets.SNOWFLAKE_CONNECTIONS_SCHEMA }}
         run: |
-          snow sql -q "ALTER GIT REPOSITORY snowflake_extensions FETCH" --temporary-connection --account $SNOWFLAKE_CONNECTIONS_ACCOUNT --user $SNOWFLAKE_CONNECTIONS_USER --password $SNOWFLAKE_CONNECTION_PASSWORD --role "$SNOWFLAKE_CONNECTIONS_ROLES" --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE --database $SNOWFLAKE_CONNECTIONS_DATABASE --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
- 
-          snow sql -q "EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/demo_project/sf_deploy_dev.sql" --temporary-connection --account $SNOWFLAKE_CONNECTIONS_ACCOUNT --user $SNOWFLAKE_CONNECTIONS_USER --password $SNOWFLAKE_CONNECTION_PASSWORD --role "$SNOWFLAKE_CONNECTIONS_ROLES" --warehouse $SNOWFLAKE_CONNECTION_WAREHOUSE --database $SNOWFLAKE_CONNECTIONS_DATABASE --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
+
+          # Actualizar repositorio en Snowflake 
+          echo "Fetching repository to Snowflake"
+          snow sql -q "ALTER GIT REPOSITORY snowflake_extensions FETCH" \
+            --temporary-connection \
+            --account $SNOWFLAKE_CONNECTIONS_ACCOUNT \
+            --user $SNOWFLAKE_CONNECTIONS_USER \
+            --password $SNOWFLAKE_CONNECTION_PASSWORD \
+            --role "$SNOWFLAKE_CONNECTIONS_ROLES" \
+            --warehouse $SNOWFLAKE_CONNECTIONS_WAREHOUSE \
+            --database $SNOWFLAKE_CONNECTIONS_DATABASE \
+            --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
+
+          # Obtener archivos modificados con extensión .sql
+          modified_files=$(git diff --name-only HEAD^ HEAD | grep '\.sql$')
+          # Iterar sobre los archivos y ejecutar el comando por cada uno
+          for file in $modified_files; do
+            snow sql -q "EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$file" \
+              --temporary-connection \
+              --account $SNOWFLAKE_CONNECTIONS_ACCOUNT \
+              --user $SNOWFLAKE_CONNECTIONS_USER \
+              --password $SNOWFLAKE_CONNECTION_PASSWORD \
+              --role "$SNOWFLAKE_CONNECTIONS_ROLES" \
+              --warehouse $SNOWFLAKE_CONNECTIONS_WAREHOUSE \
+              --database $SNOWFLAKE_CONNECTIONS_DATABASE \
+              --schema $SNOWFLAKE_CONNECTIONS_SCHEMA
+          done
  
       # ============ TEST ============
       - name: Deploy Snowflake objects to TST
